woowa-techcamp-2020/market-3

css/main.css, package-lock.json, package.json, views/main.pug
-메인페이지 마크업을 했습니다.
-CSS 디렉토리를 만들었습니다.
-nodemon을 설치했습니다. 
#7
=> [layout] 메인페이지 HTML을 작성하라

css/signUp.css, views/main.pug, views/signIn.pug, views/signUp.pug, views/signUpSuccess.pug
=> Add layout for singUp page

css/signIn.css, views/signIn.pug
=> [layout] 로그인 페이지를 마크업(HTML, CSS)하라

css/signUpSuccess.css, views/signUpSuccess.pug
=> [layout] 회원가입 성공 페이지를 마크업(HTML, CSS)하라

css/signUp.css, signUp.js, views/signUp.pug
=> [feature] 아이디 입력창을 구현하라

.gitignore, .travis.yml, README.md, package-lock.json, package.json
=> [devOps] CI를 붙여라

public/css/main.css, public/css/signIn.css, public/js/signUp.js, views/main.pug
회원가입 페이지의 아이디 입력 창 구현 javascript 코드를 함께  리팩토링 했습니다.
=> Refactor signup frontend logic

public/css/signUp.css, views/signUp.pug
ISSUE: #28 
signUp 페이지 css작업을 통해 보기좋게 화면을 개선했습니다.
=> [layout] 회원가입 페이지 마크업을 개선하라

public/css/main.css, views/main.pug
ISSUE: #29 
메인페이지 css를 수정하여 보기좋게 개선했습니다.
=> [layout] 메인 페이지의 마크업을 개선하라

public/css/signUpSuccess.css, views/signUpSuccess.pug
#38 
signUpSuccess 페이지의 css를 수정하여 보기 좋게 개선했습니다.
=> [layout] 회원가입 성공 페이지의 스타일을 개선하라

public/css/signUp.css, public/js/signUp.js, public/js/utils/domControl.js, public/js/utils/inputHandlers.js, public/js/utils/validations.js, views/signUp.pug
ISSUE: #3 
- 코드를 모듈화 했습니다.
- 비밀번호 입력창을 구현했습니다.
=> [feature] 비밀번호 입력창을 구현하라

public/css/signUp.css, public/js/signUp.js, public/js/utils/domControl.js, public/js/utils/inputHandlers.js, views/signUp.pug
=> [feature] 이메일 입력창을 구현하라

controllers/authController.js, public/js/main.js, public/js/utils/cookie.js, views/main.pug, views/signIn.pug
ISSUE: #44 
- auth/logout api를 구현했습니다
=> [feature] 로그아웃 기능을 구현하라

controllers/authController.js, controllers/userController.js, public/css/main.css, public/css/signUp.css, public/js/main.js, public/js/signIn.js, public/js/signUpSuccess.js, public/js/utils/cookie.js, views/main.pug, views/signIn.pug, views/signUp.pug, views/signUpSuccess.pug
ISSUE #23 
아래 연결을 구현했습니다.
- main -> signUp
- main -> signIn
- signIn -> main
- signIn -> signUp
- signUp -> signUpSuccess
- signUpSuccess -> main
로그아웃 기능을 위한 버튼을 구현했습니다.
=> [layout] pug 페이지들을 연결하라

public/js/signUp.js, public/js/utils/inputHandlers.js, public/js/utils/validations.js
- ISSUE: #49 
- 이름 입력 값  유효성 검사
=> [feature] 이름 입력창을 구현하라

public/css/signUp.css, public/js/signUp.js, public/js/utils/inputHandlers.js, public/js/utils/validations.js, views/signUp.pug
#50 에서 생긴 CONFLICT를 해결했습니다.
- 휴대폰번호 유효성 검사 구현
- 휴대폰번호 인증 모달창 구현
- 인증번호 시간 제한 구현
=> [feature] 휴대폰 인증 입력창을 구현하라

public/css/signUp.css, public/js/signUp.js, public/js/utils/domControl.js, public/js/utils/inputHandlers.js, views/signUp.pug
#51 의 CONFLICT를 해결했습니다.
- 주소 선택 정보 체크시 입력창 활성화 구현
- 주소 입력란 클릭시 모달창 팝업 구현
- 모달창 구현
=> [feature] 주소 입력창을 구현하라

public/js/signUp.js, public/js/utils/inputHandlers.js
#52 CONFLICT를 해결했습니다.
- 약관 동의 기능 구현
=> [feature] 약관 동의 입력창(checkbox)을 구현하라

public/js/signUp.js, public/js/utils/domControl.js, public/js/utils/inputHandlers.js, public/js/utils/validations.js
#54 의 CONFLICT를 해결했습니다.
-유효한 값을 입력하지 않은 input area로 focus
=> [feature] 회원가입 페이지 가입 완료 버튼 유효성 체크

controllers/userController.js, database/userSchema.js, services/userService.js, views/signUp.pug
- 회원가입 버튼을 눌렀을 때, db에 회원정보가 추가되도록 구현했습니다.
=> [feature] 회원가입 페이지 가입완료 버튼을 구현하라

public/css/signIn.css, public/js/main.js, public/js/signIn.js, public/js/signUp.js, public/js/utils/cookie.js, public/js/utils/domControl.js, public/js/utils/inputHandlers.js, public/js/utils/validations.js, views/main.pug, views/signIn.pug, views/signUp.pug
ISSUE: #26 
- pug에서 js를 가져오는 방식을 바꿨습니다.
- signIn 페이지의 아이디 입력창 click 이벤트에 idInputHandler를 등록했습니다.
=> [feature] 로그인 화면의 아이디 입력 오류 확인 기능을 구현하라

Procfile, app.js
=> [devOps] Heroku를 통해 배포하라

public/js/signUp.js, public/js/utils/inputHandlers.js
=> [hotfix] 회원가입페이지의  휴대폰 인증 버튼 버그 수정

public/js/signUp.js, public/js/utils/inputHandlers.js
=> [hotfix] 회원가입페이지의 가입완료 유효성 검사 버그 수정
